receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
exporters:
  file/no_rotation:
    path: /file_exporter/otel.log
  debug:
    verbosity: detailed
service:
  pipelines:
    logs:
      receivers:
        - otlp
      exporters:
        - file/no_rotation
        - debug
